/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    NavBar: typeof import('./../src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UBackTop: typeof import('uview-plus/components/u-back-top/u-back-top.vue')['default']
    UBadge: typeof import('uview-plus/components/u-badge/u-badge.vue')['default']
    UButton: typeof import('uview-plus/components/u-button/u-button.vue')['default']
    UNavbar: typeof import('uview-plus/components/u-navbar/u-navbar.vue')['default']
  }
}
