<script setup lang="ts">
import mpHtml from '@/uni_modules/uni-app/components/mp-html/mp-html.vue'

const str = `<p hexid="2c4f03b69c8a7786cd37cce86c932bb4">公式下列化学新技术可以解决的问题连线不正确的是<span parenthesis-type="Chinese" contenteditable="false" unselectable="on">（  ）</span><div class="mathrc" style="display: inline-block; line-height: 56rpx; " data-latex="\rm x=\frac {-b\pm \sqrt {{b}^{2}-4ac}} {2a}" contenteditable="false" unselectable="on">$\rm x=\frac {-b\pm \sqrt {{b}^{2}-4ac}} {2a}$</div>，<div class="mathrc" style="display: inline-block; line-height: 56rpx; " data-latex="\rm \frac {a} {\sin {A}}=\frac {b} {\sin {B}}=\frac {c} {\sin {C}}" contenteditable="false" unselectable="on">$\rm \frac {a} {\sin {A}}=\frac {b} {\sin {B}}=\frac {c} {\sin {C}}$</div>，<div class="mathrc" style="display: inline-block; line-height: 56rpx; " data-latex="\rm P=UI={I}^{2}R=\frac {{U}^{2}} {R}" contenteditable="false" unselectable="on">$\rm P=UI={I}^{2}R=\frac {{U}^{2}} {R}$</div>，<div class="mathrc" style="display: inline-block; line-height: 56rpx; " data-latex="\rm \frac {a} {\sin {A}}=\frac {b} {\sin {B}}=\frac {c} {\sin {C}}" contenteditable="false" unselectable="on">$\rm \frac {a} {\sin {A}}=\frac {b} {\sin {B}}=\frac {c} {\sin {C}}$</div>，<div class="mathrc" style="display: inline-block; line-height: 56rpx; " data-latex="\rm {F}_{浮}={\rho }_{液}g{V}_{排}" contenteditable="false" unselectable="on">$\rm {F}_{浮}={\rho }_{液}g{V}_{排}$</div>，<div class="mathrc" style="display: inline-block; line-height: 56rpx; " data-latex="\rm HCl={H}^{+}+C{l}^{-}" contenteditable="false" unselectable="on">$\rm HCl={H}^{+}+C{l}^{-}$</div>，<div class="mathrc" style="display: inline-block; line-height: 56rpx; " data-latex="\rm \frac {dy} {dx}" contenteditable="false" unselectable="on">$\rm \frac {dy} {dx}$</div>，<div class="mathrc" style="display: inline-block; line-height: 56rpx; " data-latex="\rm {}^{n}_{1}Y" contenteditable="false" unselectable="on">$\rm {}^{n}_{1}Y$</div>，<div class="mathrc" style="display: inline-block; line-height: 56rpx; " data-latex="\rm \frac {-b\pm \sqrt {{b}^{2}-4ac}} {2a}" contenteditable="false" unselectable="on">$\rm \frac {-b\pm \sqrt {{b}^{2}-4ac}} {2a}$</div>，<div class="mathrc" style="display: inline-block; line-height: 56rpx; " data-latex="\rm \tan {\theta }=\frac {\sin {\theta }} {\cos {\theta }}" contenteditable="false" unselectable="on">$\rm \tan {\theta }=\frac {\sin {\theta }} {\cos {\theta }}$</div>，<div class="mathrc" style="display: inline-block; line-height: 56rpx; " data-latex="\rm \lim_{n\rightarrow \infty } {\left ( {1+\frac {1} {n}} \right )}^{n}" contenteditable="false" unselectable="on">$\rm \lim_{n\rightarrow \infty } {\left ( {1+\frac {1} {n}} \right )}^{n}$</div>，<div class="mathrc" style="display: inline-block; line-height: 56rpx; " data-latex="\rm \max_{0\le x\le 1} {x}{e}^{-{x}^{2}}" contenteditable="false" unselectable="on">$\rm \max_{0\le x\le 1} {x}{e}^{-{x}^{2}}$</div></p>`
</script>

<template>
  <div>
    <mpHtml :content="str" />
  </div>
</template>

<style lang="scss"></style>
